---
server:
  port: 8060
  servlet:
    context-path: /loopdfs
---
datasource:
      loopdfs:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=loopdfs
        username: postgres
        password: Sikobe1+
        driver-class-name: org.postgresql.Driver
        defaultSchema:
        maxPoolSize: 20
        connectionTimeout: 60000
        idleTimeout: 600000
        maxLifetime: 1800000
        threadSleeptime: 120000
        hibernate:
          hbm2ddl.method: validate
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          timeout: 2000

swagger.enable: 'true'

logging:
  config: log4j2-spring.xml